apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: nats-streaming
  name: nats-streaming
spec:
  serviceName: nats-streaming
  replicas: 1
  template:
    metadata:
      labels:
        app: nats-streaming
    spec:
      containers:
      - name: nats-streaming
        image: 'docker.io/canhnt/nats-streaming-server:v0.5.0'
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command: 
              - /bin/sh
              - -c
              - echo $POD_NAME
        # args:
        #   - -m 8222
          # - -ft_group "ft"
          # - --cluster nats://0.0.0.0:6222
          # - --routes "nats://$LISTEN_ADDR"
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name